language: go

go:
    - 1.14.x

before_install:
    go get -d -v ./cmd/parser1c

install: true

notifications:
    email:
      on_success: change
      on_failure: always

before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1

script:
    - golangci-lint run
    - make test